wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
config:
  desc: null
  value:
    loss:
      name: bce
    model:
      name: model1
      params: 2
debug:
  desc: null
  value: true
